version: 0.4.{build}

skip_tags: true # avoid deploy to GitHub loop 

image: Visual Studio 2017

configuration:
- Release

before_build:
- nuget restore -Verbosity quiet

build:
  project: Zenseless.sln
  verbosity: minimal              # MSBuild verbosity level

after_test:
- nuget pack _Common\Zenseless.nuspec -symbols -IncludeReferencedProjects -Properties version=%APPVEYOR_BUILD_VERSION%
- nuget pack _Common\Zenseless.Sources.nuspec -IncludeReferencedProjects -Properties version=%APPVEYOR_BUILD_VERSION%

artifacts:
- path: '*.nupkg'
  name: Zenseless

deploy:
  provider: NuGet
  api_key:
    secure: w5QCSXAxezmCE9sCYev5jEuL4uAicWaB5UrXtZkSMRfHVHr1nWyJnPaJO6r+rG5j
  skip_symbols: false
  artifact: Zenseless